# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: db_development
  pool: 5
  timeout: 5000
  username: postgres
  password: z49MG2y71

test:
  adapter: postgresql
  encoding: unicode
  database: db_test
  pool: 5
  timeout: 5000
  username: postgres
  password: z49MG2y71

production:
  adapter: postgresql
  encoding: unicode
  database: db_production
  pool: 5
  timeout: 5000
  username: postgres
  password: z49MG2y71
